Update Jenkinsfile
Added lines for maven to resolve problem described below
"
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

WorkflowScript: 6: Tool type "maven" does not have an install of "maven-3.6.0" configured - did you mean "null"? @ line 6, column 15.

           maven 'maven-3.6.0' // Refers to a global tool configuration for Maven called 'maven-3.6.0'
"